name: Test App
on:
  push:
    # paths-ignore:
    #   - ".github/**"
    #   - "frontend/**"
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch : 

jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.x

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git cmake g++ libboost-program-options-dev \
          libprotozero-dev libosmium2-dev libbz2-dev zlib1g-dev liblz4-dev \
          libexpat1-dev nlohmann-json3-dev

      - name: Build and Install Osmium Tool
        run: |
          git clone https://github.com/osmcode/osmium-tool.git
          cd osmium-tool
          mkdir build
          cd build
          cmake ..
          make
          sudo make install
          sudo ldconfig

      - name: Install necessary dependencies
        run: uv sync

      - name: Install osmsg in editable mode
        run: uv pip install -e .

      - name: Generate Last hour stats
        env:
          OSM_USERNAME: ${{ secrets.OSM_USERNAME }}
          OSM_PASSWORD: ${{ secrets.OSM_PASSWORD }}
        run: |
          source .venv/bin/activate
          osmsg --format csv image --last_hour --tags 'building' 'highway' 'waterway' 'amenity' --name stats --all_tags --changeset --summary --charts
